name: Deploy Pedido on AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout inicial
      - name: Checkout Terraform repository
        uses: actions/checkout@v3

      # Configuração do Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache do Maven para acelerar builds futuros
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
          
      # Clonar o repositório da aplicação Pedido
      - name: Clone pagamento Repo
        run: git clone https://github.com/brunobucci/soat7grupo5-pedido.git pedido
  

      # Executar os testes com cobertura
      - name: Run Tests Pedido with Coverage
        run: |
          cd pedido
          mvn clean verify

      # Build da aplicação
      - name: Build Pedido Application
        run: |
          cd pedido
          mvn clean package -DskipTests

      # Verificar o arquivo .jar gerado
      - name: Verify Pedido Build Output
        run: |
          ls -l pedido/target/

      # Deploy para a instância EC2
      - name: Deploy Pedido to EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST_pedido }}
        run: |
          # Criar arquivo temporário para a chave privada
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Fazer o upload do arquivo .jar para a instância EC2
          scp -o StrictHostKeyChecking=no -i private_key.pem pedido/target/*.jar ubuntu@$AWS_HOST:/home/ubuntu/

          # Reiniciar o serviço na instância EC2
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$AWS_HOST "sudo systemctl restart pedido-app"

          # Remover a chave privada temporária
          rm -f private_key.pem
